Task5
vovkandrew/amazon-reviews-app-with-spring-boot pull request #3
Opened 2020-07-10 09:12 UTC by vovkandrew

2020-07-10 09:31 UTC, boroda4436 requested changes

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/controller/MostActiveUsersController.java
> +@RequestMapping("/most-active-users")
Я б зробив UsersController (/users) і мав би окремий метод з маппінгом /most-active

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/controller/MostActiveUsersController.java
> +    @RequestMapping("/{limit}")
Я б передавав limit як RequestParam, а не як PathVariable. PathVariable використовують тоді, коли передають певний ідентифікатор ресурсу (юзера, фільму, файла і т.д.)

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/controller/MostCommentedProductsController.java
> +    @GetMapping("/{limit}")
відписав вище

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/controller/MostCommentedProductsController.java
> +@RequestMapping("/most-commented-products")
відписав вище. Створи контроллер /products і метод /most-commented

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/controller/MostUsedWordsFromReviews.java
> +@RequestMapping("/most-used-words")
відписав вище

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/controller/MostUsedWordsFromReviews.java
> +    @RequestMapping("/{limit}")
відписав вище

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/service/ReviewService.java
> +    public Object[] findMostUsedWordsFromReviews() {
```suggestion
    public User[] findMostUsedWordsFromReviews() {
```
Можемо так?

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/service/ReviewService.java
> +                string.toLowerCase()
Старайся не розтягувати свій код
```suggestion
               String[] split = string.toLowerCase()
```

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/service/ReviewService.java
> +    private Object[] sortHashMap(HashMap<String, Integer> hashMap) {
можемо повертати не масив Object а більш вузький тип?

2020-07-10 09:31 UTC, boroda4436 commented on src/main/java/amazonreviewsapp/springboot/service/UserService.java
> +    public List<Object> findMostActiveUsers() {
```suggestion
    public List<User> findMostActiveUsers() {
```

2020-07-10 10:52 UTC, vovkandrew commented on src/main/java/amazonreviewsapp/springboot/controller/MostActiveUsersController.java
> +@RequestMapping("/most-active-users")
Fixed

2020-07-10 10:52 UTC, vovkandrew commented on src/main/java/amazonreviewsapp/springboot/controller/MostActiveUsersController.java
> +    @RequestMapping("/{limit}")
Done

2020-07-10 10:57 UTC, vovkandrew commented on src/main/java/amazonreviewsapp/springboot/service/ReviewService.java
> +    public Object[] findMostUsedWordsFromReviews() {
Изначально я думал для этого метода и для всех похожих методов придумать отдельный класс по типу ДТО и передавать из контроллера его, но то ли поленился, то ли подумал что фронту все равно из чего доставать данные, для них все джейсон (или нет?) и в итоге просто передал обджектом
В данном конкретном случае я не пойму смысл передачи массива юзеров, если по сути, нам надо передать упорядоченный массив пары слово:количество-повторений

2020-07-13 06:43 UTC, RomanDubovskyi commented on src/main/java/amazonreviewsapp/springboot/service/ReviewService.java
> +    public Object[] findMostUsedWordsFromReviews() {
краще повертати більш вузький типа динних адже, якщо твій метод повертає Object, перша ассоціація, що може прилетіти будь-що з цього методу і це не зовсім ок

2020-07-16 13:49 UTC, closed without merging